### Recuperar todas los teams
GET http://localhost:3000/teams/

### Recuperar teams por id
GET http://localhost:3000/teams/2

### Crear una teams con POST
POST http://localhost:3000/teams/
Content-Type: application/json

{
    "id":2,
    "teamname": "ameliano",
    "logo":"/img/teamslogo/ameliano.jpg",
    "stadium":"ameliano fc"
}

### Acturalizar teams
PATCH http://localhost:3000/teams/2
Content-Type: application/json

{
    "teamname":"Ameliano FC"
}

### Borrar un teams 
DELETE http://localhost:3000/teams/2